pipeline {

    agent any

    parameters {
        string(name: "PROJECT", defaultValue: "my-project", description: "Project key identifier")
        string(name: "COMPONENT", defaultValue: "my-component", description: "Component key identifier")
        choice(name: "TEMPLATE", choices: ["python-template", "java-vm-template", "java-docker-template", "java-cloud-template"], description: "Desired template that fits the tech stack for your application")
    }

    environment {
        GITEA_URL = "http://gitea:3000"
        ARTIFACTORY_URL = "http://artifactory:8082"
    }

    stages {
        stage("Create Artifactory Project") {
            steps {
                withCredentials([string(credentialsId: "ARTIFACTORY_TOKEN", variable: "TOKEN")]) {
                    sh '''curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ''' + TOKEN + '''" -d '{"project_key":"''' + PROJECT + '''", "display_name":"''' + PROJECT + '''", "admin_privileges": {"manage_members":true,"manage_resources":true,"index_resources":true},"storage_quota_bytes": -1}' $ARTIFACTORY_URL/access/api/v1/projects'''
                }
            }
        }

        stage("Create Artifactory Repository") {
            environment {
                KEY = "${PROJECT}-${COMPONENT}-local"
            }
            steps {
                withCredentials([string(credentialsId: "ARTIFACTORY_TOKEN", variable: "TOKEN")]) {
                    sh '''curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ''' + TOKEN + '''" -d '{"projectKey":"''' + PROJECT + '''", "key":"''' + KEY + '''", "rclass": "local"}' $ARTIFACTORY_URL/api/repositories/$KEY'''
                }
            }
        }

        stage("Create Gitea Organization") {
            steps {
                withCredentials([usernameColonPassword(credentialsId: "GITEA_CREDENTIALS", variable: "USERPASS")]) {
                    sh '''curl -X POST -H "Content-Type: application/json" -d '{"username":"''' + PROJECT + '''"}' -u $USERPASS $GITEA_URL/api/v1/orgs'''
                }
            }
        }

        stage("Create Gitea Repository") {
            steps {
                withCredentials([usernameColonPassword(credentialsId: "GITEA_CREDENTIALS", variable: "USERPASS")]) {
                    sh '''curl -X POST -H "Content-Type: application/json" -d '{"name":"''' + COMPONENT + '''", "owner": "''' + PROJECT + '''", "git_content": true}' -u $USERPASS $GITEA_URL/api/v1/repos/gitea/$TEMPLATE/generate'''
                }
            }
        }

        stage("Create Jenkins Pipeline") {
            environment {
                KEY = "${PROJECT}-${COMPONENT}"
                REMOTE = "${GITEA_URL}/${PROJECT}/${COMPONENT}.git"
            }
            steps {
                jobDsl scriptText: '''multibranchPipelineJob("''' + KEY + '''") {
    branchSources {
        git {
            id("''' + KEY + '''")
            remote("''' + REMOTE + '''")
        }
    }
}'''
            }
        }
    }
}
