pipeline {
    agent any

    stages {
        
        /*
        stage('Test1') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            steps {
                sh 'node --version'
            }
        }
        
        stage("Provision Infrastructure") {
            agent {
                docker { image 'hashicorp/terraform:latest' }
            }
            steps {
                sh 'terraform --version'
                sh 'terraform validate'
                sh 'terraform plan'
                sh 'terraform apply -auto-approve'
            }
        }

        stage("Configure Infrastructure") {
            steps {
                sh 'ansible-playbook'
            }
        }
        */

        stage("Test") {
            agent { image: 'python:3.11' }
            steps {
                sh 'python3 run -m pytest'
            }
        }
    }
}
