pipeline {
    agent {
        docker { image 'python:3.11' }
    }

    stages {

        stage('Validate Revision') {
            steps {
                sh 'echo Validate Revision (e.g. with Pre Commit)'
            }
        }

        stage('Provision Infrastructure') {
            steps {
                sh 'echo Provision Infrastructure (e.g. with Terraform)'
            }
        }

        stage('Configure Infrastructure') {
            steps {
                sh 'echo Configure Infrastructure (e.g. with Ansible)'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python3 -m pytest'
                }
            }
        }

        stage('Scan') {
            steps {
                sh 'echo Scan Code (e.g. with SonarQube)'
            }
        }

        stage('Build') {
            steps {
                sh 'echo Build Image'
            }
        }

        stage('Publish') {
            steps {
                sh 'echo Publish Image'
            }
        }

        stage('Deploy DEV') {
            steps {
                sh 'echo Deploy to DEV'
            }
        }

        stage('Deploy FAT') {
            steps {
                sh 'echo Deploy to FAT'
            }
        }

        stage('Deploy PROD') {
            steps {
                sh 'echo Deploy to PROD'
            }
        }

    }
}
