pipeline {
    agent {
        docker { image 'python:3.11' }
    }

    stages {
        
        stage('Install Dependencies') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python3 -m pytest'
                }
            }
        }

        stage('Build') {
            steps {
                sh 'echo Build'
            }
        }

        stage('Publish') {
            steps {
                sh 'echo Publish'
            }
        }

    }
}
